name: 'Deployment and Link'
description: 'Make a deployment with the Github Deployments API and link it to actual deployment.'
inputs:
  GITHUB_TOKEN:
    description: 'Github authorization token.'
    required: true
  ENVIRONMENT_URL:
    description: 'Link to put in deployment message.'
    required: true
  ENVIRONMENT_NAME:
    description: 'Name of deployment environment to pass to Github API.'
    required: false
    default: production
  DESCRIPTION:
    description: 'Deployment description to pass to Github API.'
    required: false
    default: ''
  MARK_SUCCEEDED:
    description: 'Should this deployment also be marked as complete/successful.'
    required: false
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.GITHUB_TOKEN }}
    - ${{ inputs.ENVIRONMENT_URL }}
    - ${{ inputs.ENVIRONMENT_NAME }}
    - ${{ inputs.DESCRIPTION }}
    - ${{ inputs.MARK_SUCCEEDED }}
