name: 'Deployment and Link'
description: 'Make a deployment with the Github Deployments API and link it to actual deployment.'
inputs:
  ENVIRONMENT_URL:
    description: 'Link to put in deployment message'
    required: true
    default: ''
  GITHUB_TOKEN:
    description: Github authorization token
    required: true
    default: ''
  DEPLOY_TYPE:
    description: Type of deployment to pass to Github API
    required: false
    default: production
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ENVIRONMENT_URL }}
    - ${{ inputs.GITHUB_TOKEN }}
    - ${{ inputs.DEPLOY_TYPE }}
