name: 'Deployment and Link'
description: 'Make a deployment with the Github Deployments API and link it to actual deployment.'
inputs:
  token:
    description: 'Github access token'
    required: true
  job_status:
    description: 'Current job status. Should never be passed; the default should be used.'
    required: false
    default: ${{ job.status }}
  ref:
    description: 'The github ref being deployed. Can be branch, tag, commit, etc.'
    required: false
  version:
    description: 'The version being deployed (for disply purposes only)'
    required: false
    default: ${{ github.sha }}

  required_contexts:
    description: |
      Comma-separated list of required status checks for this
      deployment. Default: No checks are required.
    required: false

  environment_url:
    description: 'Link to put in deployment message.'
    required: false
  environment_name:
    description: 'Name of deployment environment to pass to Github API.'
    required: false
    default: production
runs:
  using: 'node12'
  pre: 'dist/index.js'
  main: 'dist/index.js'
  post: 'dist/index.js'
