name: Release

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - name: Set Node.js 16.x
      uses: actions/setup-node@v4
      with:
        node-version: 16.x
    - name: "Install"
      run: |
        npm install
    - name: "Prettier"
      run: |
        npm run format-check
    - name: "Lint"
      run: |
        npm run lint
    - name: "Test"
      run: |
        npm run test
    - name: "build"
      run: |
        npm run build
        npm run package

  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - name: Set Node.js 16.x
      uses: actions/setup-node@v4
      with:
        node-version: 16.x
    - name: "Build action for test"
      run: |
        npm install
        npm run all
        git clean -fXd
    - name: Create Deployment
      uses: ./
      with:
        token: ${{ github.token }}
        environment_name: ${{ github.job }}
        skip_pre_action: true

  release:
    runs-on: ubuntu-22.04
    name: "Build and release action"
    needs: [build, test]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Configure git
        uses: smartlyio/github-actions@git-init-userinfo-v1
      - name: Release flow
        uses: smartlyio/github-actions@release-action-node-v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
